### ISSUE TITLE
Unable to download files

### ISSUE THREAD

**Issue by duhow** [duhow/download-github-release-assets#9]
```
Run duhow/download-github-release-assets@v1
with:
    repository: ***
    token: ***
    tag: v0.1.1
    files: microservice_wrapper-*-py3-none-any.whl
    target: microservice_wrapper-0.1.1-py3-none-any.whl
  env:
    PYTHON_VERSION: 3.9
    PIP_DISABLE_PIP_VERSION_CHECK: 1
    pythonLocation: /opt/hostedtoolcache/Python/3.9.9/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.9/x64/lib
Using GitHub repository: ***
Getting release by tag: v0.1.1
1 assets available.
1 assets selected.
Downloading microservice_wrapper-0.1.1-py3-none-any.whl with 8260 bytes to microservice_wrapper-0.1.1-py3-none-any.whl

(node:544) UnhandledPromiseRejectionWarning: HttpError: <Error><Code>AccessDenied</Code><Message>Multiple auth mechanisms are not allowed; please use either query parameters or an Authorization header</Message><Resource>github-production-release-asset-2e65be</Resource></Error>
    at /runner/_work/_actions/duhow/download-github-release-assets/v1/webpack:/download-github-release-assets/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at /runner/_work/_actions/duhow/download-github-release-assets/v1/webpack:/download-github-release-assets/src/main.js:133:1
(node:544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by duhow** [comment]
https://github.com/octokit/rest.js/issues/6#issuecomment-984897208
